[package]
name = "archive-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.25.0", features = ["full"] }
confy = "0.5.1"
serde = { version = "1.0.152", features = ["derive"] }
slack_api = "0.23.1"
chrono = "0.4.23"
